### ISSUE TITLE
GrDirectContext deallocation causes python interpreter to freeze

### ISSUE THREAD

**Issue by sven-nobs** [kyamagu/skia-python#187] opened 2023-01-23 15:53 UTC
When using the GL backend, the python interpreter seems to crash/freeze once the GrDirectContext is deallocated. I noticed this happening in my own project, but it even happens in the GL backend example from the skia-python documentation. Therefore it doesn’t seem to be a problem on my end.

Running the sample from the command line causes the freeze. The Jupyter Notebook of this repo may have the problem too, but simply doesn’t cause the entire notebook to freeze. Would be interesting to see if this problem can be reproduced by others.

**To Reproduce**
Take the following sample from the docs, save it as a .py file, then run from the command line.

```python
# Source: https://kyamagu.github.io/skia-python/tutorial/canvas.html
import skia
import glfw
import contextlib

@contextlib.contextmanager
def glfw_context():
    if not glfw.init():
        raise RuntimeError('glfw.init() failed')
    glfw.window_hint(glfw.VISIBLE, glfw.FALSE)
    glfw.window_hint(glfw.STENCIL_BITS, 8)
    window = glfw.create_window(640, 480, '', None, None)
    glfw.make_context_current(window)
    yield window
    glfw.terminate()

width, height = 200, 200
with glfw_context():
    context = skia.GrDirectContext.MakeGL()
    info = skia.ImageInfo.MakeN32Premul(width, height)
    surface = skia.Surface.MakeRenderTarget(context, skia.Budgeted.kNo, info)
    assert surface is not None

    with surface as canvas:
        canvas.drawCircle(100, 100, 40, skia.Paint(Color=skia.ColorGREEN))

    image = surface.makeImageSnapshot()
    assert image is not None
    image.save('output.png', skia.kPNG)

```

It draws and saves the circle properly, but then freezes the interpreter at the end of execution.

**Additional context**
I used a C application with an embedded python interpreter, then paused the debugger to see what happens. It seems to be repeatedly decreasing reference counts of some object. Odd, because I'd think this would cause a crash rather than a freeze. In case this problem is caused by glfw, I tried the same example with a context created using moderngl instead. The problem persists.

Python version is 3.10.
Library version of python-skia is 87.5, installed through pip.

**Workaround / Temporary Solution**
I tried increasing the reference count of the context using its ref() function:

```python
surface.recordingContext().ref()
```

And the problem went away. To ensure this isn't leaking the context, I double checked in C. The reference count reaches 0 now and the context is still deallocated properly. 

This makes me even more certain there is something fishy going on with the GrDirectContext refcount. Manually increasing reference counts doesn’t seem like intended behaviour.

**Comment by HinTak** [comment] 2023-08-02 10:20
In m88, GrContext is gone - all its methods got merged into GrDirectContext. In my m116 fork I chose to keep the shorter name, and also add an alias so using either with any of their combined methods work. So there is probably some truth in your assessment, but the problem is upstream - and Google folks make it go away in m88.

**Comment by HinTak** [comment] 2023-08-19 18:25
Not sure what's going on, with m117, it does not like the last line `image.save('output.png', skia.kPNG)`. If I comment it out the example finishes running. image.save() itself works elsewhere, so this appears to be a GPU-backed image/surface problem.

**Comment by HinTak** [comment] 2023-08-19 18:26
Simply get `RuntimeError: Failed to encode an image.`, which is not helpful.

**Comment by HinTak** [comment] 2023-11-15 05:43
I think I fixed the image save problem with m118/m119, so the example runs quickly and correctly with m120. The image.save fix is
https://github.com/kyamagu/skia-python/commit/02735056ef64d446691d9f1222c4463bf8297942

**Comment by HinTak** [comment] 2024-11-14 11:21
I tried downgrading to 87.6 (identical to 87.5 except adding later python version support) against python 3.12 on fedora, ran it a dozen of times, it takes mostly about 0.6 s to run (just "time python code.py").

You did not say what hardware/ driver you have. Here is mine:

```
b'AMD'
b'AMD Radeon R5 Graphics (radeonsi, stoney, LLVM 18.1.6, DRM 3.59, 6.11.6-200.fc40.x86_64)'
b'4.5 (Core Profile) Mesa 24.1.7'
b'4.50'
```
generated from:

```
from OpenGL.GL import glGetString, GL_VENDOR, GL_RENDERER, GL_VERSION, GL_SHADING_LANGUAGE_VERSION
print(glGetString(GL_VENDOR))
print(glGetString(GL_RENDERER))
print(glGetString(GL_VERSION))
print(glGetString(GL_SHADING_LANGUAGE_VERSION))
```

I am just going to close this as the upstream code has substantially changed since 87.x, and you probably should use v1xx ... but if you can still reproduce this with either 87.6 or x1xx, please feel free to re-open / or further comment.

**Closed by HinTak** 2024-11-14 11:21 UTC
Labels: bug
