### ISSUE TITLE
(libSkShaper) Combined emoji will be drawn as multiple emoji

### ISSUE THREAD

**Issue by Polyisoprene** [kyamagu/skia-python#195] opened 2023-07-24 07:07 UTC
**Describe the bug**
a combined emoji like ✌🏻 will be drawn as two emoji 
![image](https://github.com/kyamagu/skia-python/assets/60544083/9de23397-8b77-46b1-94c6-6256ccd1c3ae)

**To Reproduce**

```python
text = "✌🏻"
surface = skia.Surface(50,50)
paint = skia.Paint(AntiAlias=True, Color=skia.Color(0,0,0,255))
typeface = skia.FontMgr().matchFamilyStyleCharacter( "Noto Sans CJK SC",skia.FontStyle().Normal,["zh", "en"], ord(text))
font = skia.Font(typeface,10)
blob = skia.TextBlob(text, font)
canvas.drawTextBlob(blob, 30,30, paint)
```
**Expected behavior**

single emoji appears on the image

**Desktop (please complete the following information):**
 - OS: Ubuntu20.04
 - Python: 3.10
 - skia-python version: 87.5

**Additional context**

**Comment by HinTak** [comment] 2023-08-09 03:04
This sounds a lot like this upstream issue - https://github.com/google/skia/pull/129

**Comment by HinTak** [comment] 2023-10-29 09:35
Changed my mind a bit. I think the correct answer involves a text shaper. Calling a harfbuzz binding of any sort is one answer, but using skshaper is perhaps preferred. Ie. We need to bind
https://api.skia.org/classSkShaper.html

**Comment by HinTak** [comment] 2023-11-08 05:16
This is fixed in https://github.com/kyamagu/skia-python/pull/210/commits/b4331dc56cb82e0d13f4aa255be889f35a614a11 as part of #210 .

Mostly you need to do
`blob = skia.TextBlob.MakeShapedText(text, font)` instead of `blob = skia.TextBlob(text, font)`. I thought of overloading the constructor, but it is a bit hard given the constructor and `MakeShapedText` takes different set of optional arguments, so overloading the two means some arguments get ignored in the other calls. Also the returned result have different bounds, so you need to read the `blob.bounds()` and adjust offsets. BTW, I found that you made two mistakes in your typeface call (the 2nd and the last arguments are wrong). Anyway, after fixing your mistakes, and make sure a  relevant font is picked (check `typeface` - Noto Color Emoji works, and so does OpenMoji Black), it works.

@kyamagu also as a side-effect, `MakeShapedText` can handle Arabic and most of the middle East and right-to-left languages (Hebrew, Tibetan), and do the right thing for them.

**Comment by HinTak** [comment] 2023-11-08 05:25
This is a RFC for the new `MakeFromShapedText` static method. @Polyisoprene @kyamagu

**Comment by HinTak** [comment] 2023-11-08 05:28
You can cut and paste the Persian word for Harfbuzz, use an Arabic font, and have it rendered with `MakeFromShapedText`, and compare with online images, even if you don't read Arabic.

**Comment by Polyisoprene** [comment] 2023-11-08 09:13
> This is a RFC for the new `MakeFromShapedText` static method. @Polyisoprene @kyamagu

Thank you for spending so much time solving this problem, but this method seems to be ineffective。
I installed 'skia_python-120.0b4-cp310 cp310 win_amd64. whl',and i have fixed my incorrect code
```python
import skia

text = "✌🏻"
surface = skia.Surface(350,350)
canvas = surface.getCanvas()
paint = skia.Paint(AntiAlias=True, Color=skia.Color(0,0,0,255))
typeface = skia.FontMgr().makeFromFile("F:\\Python\\test\\NotoColorEmoji.ttf")
font = skia.Font(typeface,30)
blob = skia.TextBlob.MakeFromShapedText(text, font)
canvas.drawTextBlob(blob, 30,30, paint)
img = skia.Image.fromarray(canvas.toarray(colorType=skia.ColorType.kRGBA_8888_ColorType), colorType=skia.ColorType.kRGBA_8888_ColorType)
img.save("1.png")
```
but I still haven't get the correct image
[
![1](https://github.com/kyamagu/skia-python/assets/60544083/4f258b8f-617b-4ad2-9262-dc5dd744e161)
](url) 

and after running the code, I get the following output

```bash
SkIcuLoader: datafile missing: E:\Python\icudtl.dat.
SkIcuLoader: datafile missing: F:\Envs\normal\lib\site-packages\icudtl.dat.
```

**Comment by HinTak** [comment] 2023-11-08 14:56
@Polyisoprene you wrote you are on Linux:-(. I don't have icudtl in python locations, but I have 3 copies of that file on linux, under chrome/chromium and zoom/cef . The two copies under chrome/chromium are the same. All are over 10MB each. Pretty sure skia-python on Linux doesn't need it, but maybe skia-python on Windows does...

**Comment by HinTak** [comment] 2023-11-08 20:44
@Polyisoprene If it wasn't clear, I am suggesting that maybe you copy that file from either Linux chrome or Windows chrome to Windows python where that location is. I think libshaper uses harbuzz on Linux but CoreText on Mac OS. The Window equivalent of Harfbuzz on Windows is uniscribe / usp AFAIK, but I haven't come across uniscribe reference in skia's source code yet, so I have no idea how libshaper works on Windows.

**Comment by Polyisoprene** [comment] 2023-11-09 02:53
> @Polyisoprene If it wasn't clear, I am suggesting that maybe you copy that file from either Linux chrome or Windows chrome to Windows python where that location is. I think libshaper uses harbuzz on Linux but CoreText on Mac OS. The Window equivalent of Harfbuzz on Windows is uniscribe / usp AFAIK, but I haven't come across uniscribe reference in skia's source code yet, so I have no idea how libshaper works on Windows.

Thanks for your reply. Anyway, at least it works on Linux

**Comment by HinTak** [comment] 2023-11-09 07:04
I think it should work on mac os x too. If it doesn't work on Windows, that would be an upstream bug... I'd suggest try copying that file across to see if it works better.

It looks like most of that file is also shipped with nodejs on Linux as icudt73l.dat (your versioning might be different), and as part of `libicudata.so.*` . How did you build skia-python for Windows? I guess I mean did you do it the usual route (via `scripts/Build_Windows.sh`) or did you do something different? libicu is built by that script.

**Comment by Polyisoprene** [comment] 2023-11-09 08:23
> I think it should work on mac os x too. If it doesn't work on Windows, that would be an upstream bug... I'd suggest try copying that file across to see if it works better.
> 
> It looks like most of that file is also shipped with nodejs on Linux as `icudt73l.dat` (your versioning might be different), and as part of `libicudata.so.*` . How did you build skia-python for Windows? I guess I mean did you do it the usual route (via `scripts/Build_Windows.sh`) or did you do something different? libicu is built by that script.

Actually, I copied this file to the directory of Python according to the method you mentioned, but it seems not works better.And  if  copy icudt.dat to the taget directory, i will just  get a  blank PNG. I didn't build skia-python myself,but download it from Action.

do not copy 

![1](https://github.com/kyamagu/skia-python/assets/60544083/c23644ae-98c0-4953-83cf-960e0fe15574)


copy 

![1](https://github.com/kyamagu/skia-python/assets/60544083/f548d337-979c-4892-85e2-42528186cfe0)

**Comment by HinTak** [comment] 2023-11-09 14:33
Argh, in that case, I think it is an upstream bug. There is probably a matching `icudtl.dat` built.

**Comment by HinTak** [comment] 2023-11-12 01:05
I have added a test about it in my playground repo/ci : https://github.com/HinTak/skia-m1xx-python/pull/6/commits/45b25b785c8ea669bd2e00bf7a011acd293ecfa7 so it should be interesting to know on which platforms it fails.

The test is a variant of this, except I explicitly test that a string with two emojis, without and with modifier should result in exactly two glyphs at exactly the correct glyph ids. Since I am including the font itself, the agreement should be exact on all platforms.

**Comment by HinTak** [comment] 2023-11-12 07:08
CI seems to confirm your report: on Windows, two emojis one without modifier, one with, returns a count of 3 etc.

Curious enough, on Linux it only failed on python 12, still counts of two but the 2nd glyph id is not as expected, maybe a iterator lifetime issue. On mac it counts 2 also but the glyph ids are not as expected from python 3.7 .

So linux aarch64 all passes, x86_64 passed for cp37-11, but failed on the 2nd glyph id (this is curious as the first id test passes, so the glyph ids seem to change during testing, ie poorly written test...). Mac counts are correct but glyph id wrong for cp37. I am re-running the failed tests to see if the linux/mac failures is a iterator lifetime issue (ie just poorly written tests...).

But the Windows failure is an upstream one I think.

**Comment by HinTak** [comment] 2023-11-12 20:01
I have refined the tests a bit. At the moment I think the failure with Mac and Windows are different - windows can load Noto Color Emoji but cannot shape; while Mac cannot load Noto Color Emoji, so ended up loading any (`typeface` is `None`, and `Font` getting initialied with `None` which means pick any font, and is successful). On Mac, it ends up picking a generic font, but can shape and so do two glyphs of the same (i.e. likely a not-color emoji).

When the current CI run finishes (still on-going), I 'll know when Mac actually loads instead of Noto Color Emoji.

The tests probably have some object lifetime issues and needs re-runs sometimes - or it might just be that CI needs about 5 hours to run, and changes should be in batches to push, or they will collide a bit.

Anyway, I think Linux works, Mac should if you use Apple Color Emoji instead of Noto, Windows issue is upstream.

**Comment by HinTak** [comment] 2023-11-13 01:34
On Mac, it uses "Zapf Dingbats" when Noto fails to load. And glyph id 15 is about right, according to https://en.m.wikipedia.org/wiki/Zapf_Dingbats , the sign at position 13 (given notdef and null takes up two or three).

**Comment by HinTak** [comment] 2023-11-13 18:30
Filed the windows issue upstream : https://issues.skia.org/issues/310510988

**Comment by HinTak** [comment] 2023-11-15 20:52
In the tests I added, ( https://github.com/HinTak/skia-m1xx-python/pull/6/files ), initially I used NotoColorEmoji, which definitely works for Linux. Then I realised that CBDT (that particular type of colour fonts - there are 5, actually) definitely does not load on Apple, and load but not work correctly on windows, it is perhaps best to use one specific to the platform.

So here is the verdict: on Apple, the default fonts for emoji (or at least the hand sign) is Zapf Dingbats (not coloured), but you can explicitly ask for Apple Color Emoji, and both Zapf Dingbats and Apple Color Emoji works with skin color modifiers against the Apple text engine. On Windows, the Microsoft shipped colour Emoji font is Segoe UI Emoji. I actually got the exact version - 1.29 - on my local hard drive as github CI. Seguiemj 1.29 works with harfbuzz to shape, but not against libskshaper on windows. So it is definitely a bug in windows libskshaper - or lack of usage of microsoft uniscribe (don't know if it actually use harfbuzz on Windows - it shouldn't, as uniscribe is the equivalent).

So I am tempted to close this when m120 is out, and leave the windows issue for upstream.

**Comment by HinTak** [comment] 2023-11-24 00:25
#210 includes the libshaper addition (which unfortunately does not work on windows, filed at the URL above) .

#210 also includes `skia.FontMgr.New_Custom_Empty().makeFromFile(p, N)` on Windows and Mac for loading fonts via Freetype. This does not solve the windows shaping problems, but it lets you load NotoColorEmoji on Apple (which Apple's own CoreText manager doesn't let you do) and also OT-SVG color fonts on non-linux, and some font formats Apple or Microsoft don't support.

If you really want this to work on Windows, bug the Google folks at https://issues.skia.org/issues/310510988

I looked at the skia code, it only interacts with uniscribe (window's harfbuzz equivalent) in exactly one place: in a routine called `nonBmpCharToGlyph` . It might be possible to do something on skia-python side to provide access to that... but I think libSkShaper needs to be fixed for windows, probably by copying come code internally from that.

Closing for now.

**Comment by HinTak** [comment] 2024-09-20 00:01
Apparently the canonical place to get icudtl.dat is from ihttps://github.com/unicode-org/icu/releases , one of the data-bin-{l,b}.zip files. L/B for little / big endian,  and it is versioned.

**Comment by HinTak** [comment] 2024-09-24 00:09
I have figured out where to get a proper icudtl.dat, as well as where to copy it to:
https://github.com/kyamagu/skia-python/issues/268

Don't know if it makes any difference, @Polyisoprene , but see if you care to try yourself?

**Comment by HinTak** [comment] 2024-10-03 06:18
> > I think it should work on mac os x too. If it doesn't work on Windows, that would be an upstream bug... I'd suggest try copying that file across to see if it works better.
> > It looks like most of that file is also shipped with nodejs on Linux as `icudt73l.dat` (your versioning might be different), and as part of `libicudata.so.*` . How did you build skia-python for Windows? I guess I mean did you do it the usual route (via `scripts/Build_Windows.sh`) or did you do something different? libicu is built by that script.
> 
> Actually, I copied this file to the directory of Python according to the method you mentioned, but it seems not works better.And if copy icudt.dat to the taget directory, i will just get a blank PNG. I didn't build skia-python myself,but download it from Action.
> 
> do not copy
> 
> ![1](https://private-user-images.githubusercontent.com/60544083/281663878-c23644ae-98c0-4953-83cf-960e0fe15574.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MzYzODUsIm5iZiI6MTcyNzkzNjA4NSwicGF0aCI6Ii82MDU0NDA4My8yODE2NjM4NzgtYzIzNjQ0YWUtOThjMC00OTUzLTgzY2YtOTYwZTBmZTE1NTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDA2MTQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MTM5NDBiNTM4YWUyZThlYWM0NjM3NTVkYjg2OGI0ZmQzNTk2ZDg1OTM0ZDY5Nzk2OTEyOWM1ZDQ1MjQwNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ngV-Jt0Heo9w8L98bLjqONrw2Yj6-ZiLEV5tkyz7jKQ)
> 
> copy
> 
> ![1](https://private-user-images.githubusercontent.com/60544083/281664104-f548d337-979c-4892-85e2-42528186cfe0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MzYzODUsIm5iZiI6MTcyNzkzNjA4NSwicGF0aCI6Ii82MDU0NDA4My8yODE2NjQxMDQtZjU0OGQzMzctOTc5Yy00ODkyLTg1ZTItNDI1MjgxODZjZmUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDA2MTQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjYWI0NjlhNTI2NTFiNWY4MDZjZDAxOTY3OTk2NWY3YzJmODlmMTdmODA2MjJiYjJlZWE2N2FlNmQ3ZmY3NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uURXejGFCeIzZy6BTBCID6SXelkTjb_KaZ2KJaTQta0)

I seems to have just reproduced this breakage - although copying a icudtl into some place allow skparagraph to load properly, it seems to break 
`MakeFromShapedText` :

https://github.com/kyamagu/skia-python/pull/270#issuecomment-2390603817

This is all Windows specific.

**Comment by HinTak** [comment] 2024-11-03 20:23
Just to cover old ground - upto m125 you need v69, while from m126 onwards you need v74:
https://github.com/kyamagu/skia-python/pull/270/commits/2b6ab54ea4c109583f0b28c67dfb246d00a0d01c

This part of code is somewhat sensitive to the icudtl version if you have to copy one (on windows)

**Comment by HinTak** [comment] 2024-11-03 20:26
Revisit the windows issue, now we know we needs to be specific about icudtl version.

**Comment by HinTak** [comment] 2024-11-04 08:27
@Polyisoprene testing shows that version-matching icudtl.dat is the issue - on windows, you needs exactly v74 .

**Comment by HinTak** [comment] 2024-11-05 16:28
@Polyisoprene #279 includes the fix for windows, and also a variant of your code above to test within CI on all platforms (counting how many glyphs we get, and the the expected number, not more), to make sure that it works. Give that a try on windows, or we'll merge it for the next release anyway.

**Comment by BalconyJH** [comment] 2024-11-06 06:56
Thank you for the work in #279. It’s working great on Windows now, and all combined emoji render correctly as expected. Appreciate the effort to make this run smoothly across platforms.

**Comment by HinTak** [comment] 2024-11-14 03:10
#279 merged. M132 going out tomorrow.

**Closed by HinTak** 2024-11-14 03:10 UTC
Labels: enhancement
